# Generated by Django 4.2 on 2023-04-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
