# Generated by Django 4.2 on 2023-04-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_review_this_draft_alter_review_this_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='experience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
