# Generated by Django 4.2 on 2023-04-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customer_temp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='description',
            field=models.TextField(blank=True, max_length=14000, null=True),
        ),
    ]
