# Generated by Django 4.2 on 2023-04-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_draft_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='description',
            field=models.TextField(blank=True, max_length=80000, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='subtitle',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='title',
            field=models.TextField(max_length=40000, null=True),
        ),
    ]
