# Generated by Django 4.2 on 2023-05-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_draft_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
