# Generated by Django 4.2 on 2023-05-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_draft_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='Drafts'),
        ),
    ]
