# Generated by Django 4.2 on 2023-04-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_draft_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
